// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS20JqM445qNC2gnk4dz8nAM41NNDx5_c',
    appId: '1:1091795673748:web:5e330ef6590eef4026ca81',
    messagingSenderId: '1091795673748',
    projectId: 'instragram-api-5f2b7',
    authDomain: 'instragram-api-5f2b7.firebaseapp.com',
    storageBucket: 'instragram-api-5f2b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFu0oXzoFlZTwH9sII_osh6WAON5kAXs0',
    appId: '1:1091795673748:android:ced8bcbe4103649b26ca81',
    messagingSenderId: '1091795673748',
    projectId: 'instragram-api-5f2b7',
    storageBucket: 'instragram-api-5f2b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdUacLfG6Vgg36jx4wokjZAPYeIPUP5g4',
    appId: '1:1091795673748:ios:ea2b18ccbf16b3bc26ca81',
    messagingSenderId: '1091795673748',
    projectId: 'instragram-api-5f2b7',
    storageBucket: 'instragram-api-5f2b7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdUacLfG6Vgg36jx4wokjZAPYeIPUP5g4',
    appId: '1:1091795673748:ios:ea2b18ccbf16b3bc26ca81',
    messagingSenderId: '1091795673748',
    projectId: 'instragram-api-5f2b7',
    storageBucket: 'instragram-api-5f2b7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS20JqM445qNC2gnk4dz8nAM41NNDx5_c',
    appId: '1:1091795673748:web:bf09ef12c60592a226ca81',
    messagingSenderId: '1091795673748',
    projectId: 'instragram-api-5f2b7',
    authDomain: 'instragram-api-5f2b7.firebaseapp.com',
    storageBucket: 'instragram-api-5f2b7.appspot.com',
  );
}
